// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhwZ3X7pvcdzKwdtuAnv15u6jW5wEKNF0',
    appId: '1:369609442925:web:30ab529108db27e25ea164',
    messagingSenderId: '369609442925',
    projectId: 'grocery-app-a86dc',
    authDomain: 'grocery-app-a86dc.firebaseapp.com',
    storageBucket: 'grocery-app-a86dc.firebasestorage.app',
    measurementId: 'G-P43LLNHH7C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlLuokE5ryr_7-7ODGp1JyjvM3d5s7lWc',
    appId: '1:369609442925:android:cad9c6f23daca7255ea164',
    messagingSenderId: '369609442925',
    projectId: 'grocery-app-a86dc',
    storageBucket: 'grocery-app-a86dc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3Tz4317QrnG6LyE0H2SXv1Y6lia9XJzw',
    appId: '1:369609442925:ios:30e3c7d95027a3c95ea164',
    messagingSenderId: '369609442925',
    projectId: 'grocery-app-a86dc',
    storageBucket: 'grocery-app-a86dc.firebasestorage.app',
    iosBundleId: 'com.example.groceryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3Tz4317QrnG6LyE0H2SXv1Y6lia9XJzw',
    appId: '1:369609442925:ios:30e3c7d95027a3c95ea164',
    messagingSenderId: '369609442925',
    projectId: 'grocery-app-a86dc',
    storageBucket: 'grocery-app-a86dc.firebasestorage.app',
    iosBundleId: 'com.example.groceryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhwZ3X7pvcdzKwdtuAnv15u6jW5wEKNF0',
    appId: '1:369609442925:web:caae17cec8a177c65ea164',
    messagingSenderId: '369609442925',
    projectId: 'grocery-app-a86dc',
    authDomain: 'grocery-app-a86dc.firebaseapp.com',
    storageBucket: 'grocery-app-a86dc.firebasestorage.app',
    measurementId: 'G-24HSTCLNH6',
  );
}
